[storage_backend]
storage_type = "LocalFs"

[storage_backend.backends.local_fs]
dir_path = "/etc/kbs/repository"

# Disable HTTPS for simplicity in testing
[http_server]
sockets = ["0.0.0.0:8080"]
insecure_http = true

[admin]
# Do not use this in production.
authorization_mode = "InsecureAllowAll"

[attestation_token]
insecure_header_jwk = true

[[plugins]]
name = "resource"
storage_backend_type = "kvstorage"

